module

public import C4

@[expose] public section

#print axioms C4.theoremB_weak
#print axioms C4.theoremA
#print axioms C4.theoremA_cyclic
#print axioms C4.theoremA_slice
#print axioms C4.albouy_square
#print axioms C4.Shape.contMDiffOn_fS
#print axioms C4.Shape.critical_iff
#print axioms C4.convex_shape_min
#print axioms C4.nondegenerate
#print axioms C4.nondegenerate_slice
#print axioms C4.theoremA_two
#print axioms C4.theoremA_analytic
#print axioms C4.theoremA_analytic_slice
#print axioms C4.corollaryC_i
#print axioms C4.corollaryC_ii
#print axioms C4.massMap_spec
#print axioms C4.ccr_mass_injective
#print axioms C4.ccr_injective
#print axioms C4.convex_count
#print axioms C4.convex_count_OP
#print axioms C4.corollaryD_a
#print axioms C4.corollaryD_b
#print axioms C4.corollaryD_c
#print axioms C4.hessian_Phi
#print axioms C4.hessian_q
#print axioms C4.hessian_rigid
#print axioms C4.shape_decomp
#print axioms C4.shape_tangent
#print axioms C4.shape_hessian
#print axioms C4.shape_index
#print axioms C4.shape_nondegenerate_iff
#print axioms C4.shape_localMin_iff
#print axioms C4.area_sum_eq_zero
#print axioms C4.area_moment_eq_zero
#print axioms C4.area_simc
#print axioms C4.area_mirror
#print axioms C4.area_eq_zero_of_eq
#print axioms C4.area_eq_zero_iff_collinear
#print axioms C4.order1234_iff
#print axioms C4.order1234_ccw
#print axioms C4.isConvex_iff_order
#print axioms C4.isConvex_iff_not_interior
#print axioms C4.concave_interior
#print axioms C4.dr_eq_zero_iff
#print axioms C4.selfStress_iff
#print axioms C4.hessK_eq_zero_iff
#print axioms C4.nocollinear
#print axioms C4.dziobek
#print axioms C4.convex_signs
#print axioms C4.convex_diagonal_longer
#print axioms C4.dziobek_products
#print axioms C4.longest_side_opposite
#print axioms C4.hessQ_identity_abs
#print axioms C4.palmore_shape
#print axioms C4.palmore
#print axioms C4.dziobekFn_w
#print axioms C4.dziobekFn_F
#print axioms C4.cc_iff_P
#print axioms C4.masses_unique
#print axioms C4.cc_masses
#print axioms C4.normal_cc
#print axioms C4.normal_exists
#print axioms C4.normal_injective
#print axioms C4.ShapeHessAux.hessian_fUI_display
#print axioms C4.prZ_isProperMap
#print axioms C4.not_collinear_limit
#print axioms C4.quad_area
#print axioms C4.Shape.contMDiffAt_proj
#print axioms C4.eta_props
#print axioms C4.qd_similarOP_eq
#print axioms C4.normalize_sim
#print axioms C4.dir_cap
#print axioms C4.ch_cap
#print axioms C4.dirCover
#print axioms C4.chCover
